<a href="https://colab.research.google.com/github/saurabhkr78/100-days-ML/blob/main/KNN_model.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''A retail company wants to predict customer purchasing bahvipur based on their age,salary,and past purchase history.
The KNN is used to classify potential customers to personalie marketing strategies in order to help in understanding ,targeting specific customer segmeent effectvely thereby increasing sales and customer satisfaction'''


In [1]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier


In [7]:
#features extraction
data=np.array([[25,50000,2],[30,80000,1],[20,30000,2],[40,90000,1],[45,75000,2],[48,850000,1]])
labels=np.array([1,2,1,0,2,1]) #0-low  1-medium 2-high

In [8]:
#split the data into training and testing data
X_train,X_test,y_train,y_test=train_test_split(data,labels,test_size=0.2,random_state=42)


In [10]:
#data standardization
Scaler=StandardScaler()
#overriding data
X_train=Scaler.fit_transform(X_train)
X_test=Scaler.fit_transform(X_test)

In [11]:
#training of model
knn=KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=3)

In [15]:
#accuracy
accuracy=knn.score(X_test,y_test)
print(f"model accuracy is: {accuracy}")

model accuracy is: 0.0


In [16]:
#user-input
user_input=np.array([[25,50000,2]])
#need to perform standard scaling
user_input_scaled=Scaler.fit_transform(user_input)
knn.predict(user_input_scaled)

array([0])

In [17]:
#user-input
user_input=np.array([[32,70000,2]])
#need to perform standard scaling
user_input_scaled=Scaler.fit_transform(user_input)
knn.predict(user_input_scaled)

array([0])

In [18]:
#user-input
user_input=np.array([[30,30000,5]])
#need to perform standard scaling
user_input_scaled=Scaler.fit_transform(user_input)
knn.predict(user_input_scaled)

array([0])